import { 
  Document, 
  Packer, 
  Paragraph, 
  TextRun, 
  HeadingLevel, 
  AlignmentType, 
  Table, 
  TableRow, 
  TableCell, 
  BorderStyle, 
  WidthType,
  SectionType,
  Header,
  Footer,
  PageNumber,
  NumberFormat,
  ExternalHyperlink
} from "docx";
import { saveAs } from "file-saver";

export const generateInterviewWordReport = async (report: any) => {
  const doc = new Document({
    sections: [
      {
        properties: {
          type: SectionType.NEXT_PAGE,
        },
        headers: {
          default: new Header({
            children: [
              new Paragraph({
                children: [
                  new TextRun({
                    text: "InterviewForge AI Intelligence Report",
                    bold: true,
                    color: "2563EB",
                    size: 24,
                  }),
                ],
                alignment: AlignmentType.RIGHT,
              }),
            ],
          }),
        },
        footers: {
          default: new Footer({
            children: [
              new Paragraph({
                alignment: AlignmentType.CENTER,
                children: [
                  new TextRun("Confidential - Generated by InterviewForge AI"),
                  new TextRun({
                    children: [" - Page ", PageNumber.CURRENT, " of ", PageNumber.TOTAL_PAGES],
                  }),
                ],
              }),
            ],
          }),
        },
        children: [
          // Title Page Header
          new Paragraph({
            text: "CANDIDATE INTELLIGENCE REPORT",
            heading: HeadingLevel.HEADING_1,
            alignment: AlignmentType.CENTER,
            spacing: { before: 400, after: 400 },
          }),

          // Main Info Table
          new Table({
            width: { size: 100, type: WidthType.PERCENTAGE },
            rows: [
              new TableRow({
                children: [
                  new TableCell({
                    children: [new Paragraph({ children: [new TextRun({ text: "Candidate Name", bold: true })] })],
                    shading: { fill: "F1F5F9" },
                  }),
                  new TableCell({
                    children: [new Paragraph(report.candidateName)],
                  }),
                  new TableCell({
                    children: [new Paragraph({ children: [new TextRun({ text: "Match Score", bold: true })] })],
                    shading: { fill: "F1F5F9" },
                  }),
                  new TableCell({
                    children: [new Paragraph({ children: [new TextRun({ text: `${report.matchScore}%`, bold: true, color: "10B981" })] })],
                  }),
                ],
              }),
              new TableRow({
                children: [
                  new TableCell({
                    children: [new Paragraph({ children: [new TextRun({ text: "Target Role", bold: true })] })],
                    shading: { fill: "F1F5F9" },
                  }),
                  new TableCell({
                    children: [new Paragraph(report.jobTitle)],
                  }),
                  new TableCell({
                    children: [new Paragraph({ children: [new TextRun({ text: "Risk Level", bold: true })] })],
                    shading: { fill: "F1F5F9" },
                  }),
                  new TableCell({
                    children: [new Paragraph({ children: [new TextRun({ text: report.riskLevel, bold: true, color: report.riskLevel === 'Low' ? '10B981' : report.riskLevel === 'High' ? 'EF4444' : 'F59E0B' })] })],
                  }),
                ],
              }),
            ],
          }),

          new Paragraph({ text: "", spacing: { after: 400 } }),

          // Executive Summary
          new Paragraph({
            text: "EXECUTIVE SUMMARY",
            heading: HeadingLevel.HEADING_2,
            border: { bottom: { color: "CBD5E1", space: 1, style: BorderStyle.SINGLE, size: 6 } },
            spacing: { before: 400, after: 200 },
          }),
          new Paragraph({
            children: [
              new TextRun({
                text: report.candidateSummary || "No summary available.",
                italics: true,
              }),
            ],
            spacing: { after: 400 },
          }),

          // Interview Strategy
          new Paragraph({
            text: "INTERVIEW STRATEGY",
            heading: HeadingLevel.HEADING_2,
            border: { bottom: { color: "CBD5E1", space: 1, style: BorderStyle.SINGLE, size: 6 } },
            spacing: { before: 400, after: 200 },
          }),
          new Paragraph({
            text: report.interviewStrategy || "Standard technical evaluation recommended.",
            spacing: { after: 400 },
          }),

          // Strengths & Gaps
          new Paragraph({
            text: "KEY EVALUATION PILLARS",
            heading: HeadingLevel.HEADING_2,
            border: { bottom: { color: "CBD5E1", space: 1, style: BorderStyle.SINGLE, size: 6 } },
            spacing: { before: 400, after: 200 },
          }),
          new Paragraph({
            children: [new TextRun({ text: "Primary Strengths", bold: true, color: "10B981" })],
          }),
          ...(report.strengths || []).map((s: string) => new Paragraph({ text: `• ${s}`, indent: { left: 720 } })),
          
          new Paragraph({ text: "", spacing: { before: 200 } }),
          
          new Paragraph({
            children: [new TextRun({ text: "Identified Gaps / Growth Areas", bold: true, color: "F59E0B" })],
          }),
          ...(report.gaps || []).map((g: string) => new Paragraph({ text: `• ${g}`, indent: { left: 720 } })),

          // Questions
          new Paragraph({
            text: "CURATED INTERVIEW KITS",
            heading: HeadingLevel.HEADING_2,
            border: { bottom: { color: "2563EB", space: 1, style: BorderStyle.SINGLE, size: 12 } },
            spacing: { before: 600, after: 400 },
          }),

          ...(report.questions || []).map((q: any, i: number) => [
            new Paragraph({
              children: [
                new TextRun({ text: `Q${i + 1}: ${q.text}`, bold: true, size: 28 }),
              ],
              spacing: { before: 300, after: 100 },
            }),
            new Paragraph({
              children: [
                new TextRun({ text: `Category: ${q.category || 'General'} | Priority: ${'★'.repeat(q.weight || 3)}`, color: "64748B", size: 20 }),
              ],
              spacing: { after: 200 },
            }),
            new Table({
              width: { size: 100, type: WidthType.PERCENTAGE },
              rows: [
                new TableRow({
                  children: [
                    new TableCell({
                      children: [
                        new Paragraph({
                          children: [
                            new TextRun({ text: "Ideal Answer / Key Points to Look For:", bold: true, color: "2563EB" }),
                          ],
                          spacing: { after: 100 },
                        }),
                        new Paragraph({
                          children: [
                            new TextRun({ text: q.idealAnswer, italics: true }),
                          ],
                        }),
                      ],
                      shading: { fill: "F8FAFC" },
                      margins: { top: 200, bottom: 200, left: 200, right: 200 },
                    }),
                  ],
                }),
              ],
            }),
            new Paragraph({ text: "", spacing: { after: 400 } }),
          ]).flat(),

          // Risk & Verification
          new Paragraph({
            text: "INTEGRITY & VERIFICATION CHECKLIST",
            heading: HeadingLevel.HEADING_2,
            border: { bottom: { color: "EF4444", space: 1, style: BorderStyle.SINGLE, size: 6 } },
            spacing: { before: 400, after: 200 },
          }),
          new Paragraph({
            children: [new TextRun({ text: "Red Flags to Probe", bold: true, color: "EF4444" })],
          }),
          ...(report.redFlags || ["No significant red flags detected."]).map((f: string) => new Paragraph({ text: `□ ${f}`, indent: { left: 720 } })),
          
          new Paragraph({ text: "", spacing: { before: 200 } }),
          
          new Paragraph({
            children: [new TextRun({ text: "Claims to Verify", bold: true, color: "F59E0B" })],
          }),
          ...(report.resumeClaimsToVerify || []).map((c: string) => new Paragraph({ text: `□ ${c}`, indent: { left: 720 } })),
        ],
      },
    ],
  });

  const blob = await Packer.toBlob(doc);
  saveAs(blob, `InterviewForge_Report_${report.candidateName.replace(/\s+/g, '_')}.docx`);
};
